### ISSUE TITLE
How can I index & search my own images?

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#10]
I put some images in my ec2 instance's "/mnt/nyc_images/" fold, and run the 
> fab index &

it work well, and the "/mnt/nyc_index/" has the index files

but when I run
> python server.py &  

 and search with image, it get nothing

when I Run demo with precomputed index, I found the images path in the index files is not in my ec2, or did I need mount a S3 bucket on the EC2?

**Comment by AKSHAYUBHAT** [comment]
Edit the file settings.py and set 
`DEMO = False`
https://github.com/AKSHAYUBHAT/VisualSearchServer/blob/master/settings.py

Did you do approximate search or exact search?
Use exact search. You might want to try closing the server and restarting it. 

You surely don't need to mount the S3 bucket on EC2 again. 
This function retrieves individual files and should work correctly when DEMO = False.
