### ISSUE TITLE
What the relation about index extracted by pool3 features And the features  derived from Google's inception model 

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#11]
> Are the  features that used to extract index are the same with the   features  derived from Google's inception model ?

**Comment by AKSHAYUBHAT** [comment]
Yes, specifically the features are output of the pool_3 layer / operation.

**Comment by AKSHAYUBHAT** [comment]
https://github.com/AKSHAYUBHAT/VisualSearchServer/blob/master/notebooks/notebook_network.ipynb
