### ISSUE TITLE
Unable to index images properly

### ISSUE THREAD

**Issue by himanshunimje** [AKSHAYUBHAT/VisualSearchServer#14]
Hi,

I am trying to index a new set of images using this code. For the same, I have uploaded the all the image files to a custom_images folder in '/mnt/'. I have also changed the relevant DATAPATH & INDEXPATH in settings.py.

However, while running the command 'fab index', I am encountering the following errors for EACH of the images:

```
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:475] Sum Total of in-use chunks: 24.38MiB

W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:211] Ran out of memory trying to allocate 640B.  See logs for memory state

W tensorflow/core/kernels/constant_op.cc:38] Internal: Dst tensor is not initialized.

E tensorflow/core/common_runtime/executor.cc:275] Executor failed to create kernel. Internal: Dst tensor is not initialized.

[[Node: mixed_6/tower_1/conv_2/batchnorm/beta = Const[dtype=DT_FLOAT, value=Tensor<type: float shape: [160] values: -0.31545049 -0.80871856 -0.49472183...>, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

Can you please help me understand the reason for this issue? 

Also, are there are any pre set parameters that I need to change depending on the size & content of images for better results?

Thanks

**Comment by AKSHAYUBHAT** [comment]
Hi please try the updated version which is compatible with the latest version of tensorflow, though it seems this is due to GPU running out of memory.
