### ISSUE TITLE
Questions on process

### ISSUE THREAD

**Issue by rememberlenny** [AKSHAYUBHAT/VisualSearchServer#17]
Hey @AKSHAYUBHAT 

Thanks for responding to previous questions.

Can you write a bit around your suggestions for the follow:
- How to use spot instance and keep servers operating after termination/restart
- How to setup your own S3 instance to pull images into
- Best practices for adding files to the server without losing them after spot server termination/restart

Thank you!

**Comment by AKSHAYUBHAT** [comment]
I now have a new project that works without having a hard dependency on AWS. It uses Django, Docker-compose to allow users to both upload, index and query both videos and collection of images. It currently implements all the basic functionality but I will finish a beta release by end of Feb. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics

**Comment by rememberlenny** [comment]
@akshayjbhat I'd love to help with this. I'm working a lot with bosh and software containerization. Are you working locally or off a branch?
