### ISSUE TITLE
  Document questions

### ISSUE THREAD

**Issue by yghcats** [AKSHAYUBHAT/VisualSearchServer#18]
Hello! Would like to know your project, you can not understand this document：https://github.com/AKSHAYUBHAT/VisualSearchServer ,  you can give a specific document?

Thank you!

**Comment by AKSHAYUBHAT** [comment]
Please check out the new project I am developing which will hopefully have better documentation but guaranteed to have more functionality. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
