### ISSUE TITLE
network.pb question

### ISSUE THREAD

**Issue by skhater17** [AKSHAYUBHAT/VisualSearchServer#19]
Hello,

I want to exchange the network.pb with my own trained network graph. i tried to replace the network.pb in the data folder with mine, and then i got an error

"Executor failed to create kernel.  Invalid argument: NodeDef mentions attr 'dct_method' not in op,name=DecodeJpeg;"

I tried to search for this error, and knew it might be of different versions of tensorflow.

Now i updated the tensorflow version to 0.12.1 which is the same version of the Docker container one, but still the error exists,

Any help?
Thanks

**Comment by AKSHAYUBHAT** [comment]
DecodeJpeg is the operation which which transforms the JPEG image byte array into a 3 dimensional tensor. Its likely that your network has some other operation which is involved in loading an image. 
This notebook contains all operations/nodes implemented in the inception network.pb.

To use with this project you only need a DecodePNG or DecodeJPG operation and a corresponding Pool3 or other operation where you generate indexing vector. 
https://github.com/AKSHAYUBHAT/VisualSearchServer/blob/master/notebooks/notebook_network.ipynb

I have also stopped working on this project and will be releasing Deep Video Analytics, which contains the same functionality as this project but an complete UI to not only search on precomputed indexes but also to allow users to upload videos/images. That project however uses PyTorch with ResNet. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
