### ISSUE TITLE
Having issues building

### ISSUE THREAD

**Issue by jamesmgg** [AKSHAYUBHAT/VisualSearchServer#20]
I think this is not related to your repo, but I am not 100% sure... I tried many things to try to fix these errors, but still no luck. Any ideas why I'm getting the following errors?

Main errors:
`c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory`
`build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory`

Full error output:
https://gist.github.com/jamesmgg/8d6678a3d085b25144092a95c4a13e3e

**Comment by AKSHAYUBHAT** [comment]
Fixed, try by pulling latest commit. It was most likely due to change in the gcr.io tensorflow image.

**Comment by jamesmgg** [comment]
Awesome. Thank you!
