### ISSUE TITLE
Missing S3 files?

### ISSUE THREAD

**Issue by jamesmgg** [AKSHAYUBHAT/VisualSearchServer#21]
When running `fab demo_fasion` or `fab demo_nyc` it says there is no such file. If they were removed then maybe README can be updated to reflect that.
![image](https://cloud.githubusercontent.com/assets/774806/22869189/c72029ee-f162-11e6-9499-8c546388a77a.png)

**Comment by AKSHAYUBHAT** [comment]
The error means that there is no /mnt/ folder to download the files to, you can edit fabfile.py and replace /mnt/ with any other path. 
I have stopped working on this project and developing better project with far more functionality including user uploads, video handling, object detection etc. https://github.com/AKSHAYUBHAT/DeepVideoAnalytics
