### ISSUE TITLE
Recreate network.pb file

### ISSUE THREAD

**Issue by eldor4do** [AKSHAYUBHAT/VisualSearchServer#3]
How do I recreate the network.pb file?

**Comment by AKSHAYUBHAT** [comment]
Network.pb is provided by Google through tensor flow. 

See this for more information : https://www.tensorflow.org/versions/r0.7/tutorials/image_recognition/index.html


> classify_image.py downloads the trained model from tensorflow.org when the program is run for the first time. You'll need about 200M of free space available on your hard disk.
> 
> The following instructions assume you installed TensorFlow from a PIP package and that your terminal resides in the TensorFlow root directory.
> 
> cd tensorflow/models/image/imagenet
> python classify_image.py
> The above command will classify a supplied image of a panda bear.
> 
>
