### ISSUE TITLE
Hello, Thank you for you code, but how can i run this project on my own computer?

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#4]

**Comment by AKSHAYUBHAT** [comment]
I am adding instructions along with list of necessary dependencies in form of a requirements.txt.
Please check back in a week or two.

**Comment by hasegetc** [comment]
thank you very much!!!

**Comment by AKSHAYUBHAT** [comment]
Hi I have significantly updated the code. please see the readme and setup task in the fabfile.py for instructions and required packages.
