### ISSUE TITLE
availability of AMI?

### ISSUE THREAD

**Issue by trtg** [AKSHAYUBHAT/VisualSearchServer#5]
ami-b80f0ad2 isn't turning up in the list of community AMIs, have you taken it down?

**Comment by AKSHAYUBHAT** [comment]
Are you looking in the correct AWS region, its present in Northern Virginia (US-east-1). You can change from drop down menu on upper right corner in console. I made sure to use my second account and running/testing AMI.

**Comment by trtg** [comment]
Thanks, I was indeed looking in the wrong region.
