### ISSUE TITLE
I follow the "Run demo with precomputed index", but get some wrong

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#7]
I use the "fab demo_fashion" command, but get this wrong message

[localhost] local: aws s3api get-object --bucket aub3visualsearch --key "fashion_index.tar.gz" --request-payer requester /mnt/fashion_index.tar.gz

did i miss sth?

I am a new use of aws :(

**Comment by AKSHAYUBHAT** [comment]
This is not a wrong message its just downloading the index from AWS it will take several minutes since the index itself is few Gbs. try navigating to "cd /mnt/" and check if you can see the file being downloaded.

**Comment by hasegetc** [comment]
Fatal error: local() encountered an error (return code 255) while executing 'aws s3api get-object --bucket aub3visualsearch --key "fashion_index.tar.gz" --request-payer requester /mnt/fashion_index.tar.gz'

Sorry, I paste the wrong message, above is the error

**Comment by AKSHAYUBHAT** [comment]
Can you run the following command from the ssh terminal? 
`aws s3api get-object --bucket aub3visualsearch --key "fashion_index.tar.gz" --request-payer requester /mnt/fashion_index.tar.gz`
And report the error.

**Comment by hasegetc** [comment]
Hello:
this is the info:)

>A client error (InvalidAccessKeyId) occurred when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by AKSHAYUBHAT** [comment]
You need to use either AWS IAM roles or run "AWS configure" and enter correct AWS key & secret. Ifor you are running it on AWS EC2 I highly recommend using AWS IAM role with s3 read permission.

**Comment by hasegetc** [comment]
* hi, I create one bucket on my aws,add the seceret key in it , and run "aws configure", add my id and key,then run "fab demo_fashion", here are the error info

> A client error (InvalidAccessKeyId) occurred when calling the GetObject operation: The AWS Access Key Id you provided does not exist in our records.

> Fatal error: local() encountered an error (return code 255) while executing 'aws s3api get-object --bucket aub3visualsearch --key "fashion_index.tar.gz" --request-payer requester /mnt/fashion_index.tar.gz'

Aborting.

**Comment by AKSHAYUBHAT** [comment]
Can you run :

aws s3 ls

You should see list of your buckets , otherwise it's misconfigured.
Have you followed this.
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by AKSHAYUBHAT** [comment]
The error message means that the AccessKey (it works like your username) cannot be found. Which means that either IAM roles have not been set up or you have not run AWS configure with valid AccessID & Key

**Comment by hasegetc** [comment]
> I hava get the file,Thank you very much for your patience :)
