### ISSUE TITLE
could you put the data on a http download website

### ISSUE THREAD

**Issue by hasegetc** [AKSHAYUBHAT/VisualSearchServer#8]
Hi, I am trouble you again. 

for China's Great firewall, I cant use **"aws s3api get-object"** to download the data from aws, I have to use the VPN to do that, but It also too slow and always break down.

May I ask you to put the data on a http download website? :)
Sorry for trouble you!

**Comment by AKSHAYUBHAT** [comment]
Hi, you would still need images to work, which also use aws s3api calls. you might want to consider getting an AWS instance. even the one within a free tier should let you use it.
